Repository myk-org/github-webhook-server, pull requests merged in 2022-09, with the labels that each got.

#1 Generic webhook
  github-webhook-server-container/__init__.py
  github-webhook-server-container/app.py
  github-webhook-server-container/github_api.py
  github-webhook-server-container/webhook.py
Labels: size/XXL

#3 Add gitlab API
  .github/workflows/code-check.yml
  docker-compose.yaml
  example.config.yaml
  webhook-server-container/Dockerfile
  webhook-server-container/app.py
  webhook-server-container/entrypoint.sh
  webhook-server-container/gitlab_api.py
  webhook-server-container/requirements.txt
  webhook-server-container/webhook.py
Labels: size/XL

#8 Update welcome message
  webhook-server-container/gitlab_api.py
Labels: size/XS, Approved-by-myakove

#6 Always make sure that the repository's merge requests 'All threads must be resolved' setting is enabled
  webhook-server-container/gitlab_api.py
Labels: size/XS, Approved-by-myakove

#10 Remove gitlab approve/unapproave functionality
  webhook-server-container/gitlab_api.py
Labels: size/XS, Approved-by-myakove

#12 split process_webhook to functions
  OWNERS
  webhook-server-container/app.py
  webhook-server-container/github_api.py
Labels: verified, size/L

#17 cherry-pick: check if source branch exists
  webhook-server-container/github_api.py
Labels: verified, size/S

#19 Unify reviewers mention into one comment
  webhook-server-container/gitlab_api.py
Labels: size/XS, Approved-by-myakove, verified

#23 Log exceptions and note body
  webhook-server-container/app.py
  webhook-server-container/gitlab_api.py
Labels: Approved-by-myakove, verified, size/S, branch-main

#25 Do not resolve/unresolve welcome note for PRs without welcome note
  webhook-server-container/gitlab_api.py
Labels: Approved-by-myakove, size/S, branch-main

#27 Gitlab: Add welcome note logs
  webhook-server-container/gitlab_api.py
Labels: size/XS, Approved-by-myakove, verified, branch-main
