Repository myk-org/github-webhook-server, pull requests merged in 2023-06, with the labels that each got.

#133 Configure Renovate
  renovate.json
Labels: size/XS, verified, branch-main

#135 Update dependency poetry-dynamic-versioning to ^0.22.0
  poetry.lock
  pyproject.toml
Labels: size/XS, verified, branch-main

#143 Update dependency tox to v4.6.0
  poetry.lock
Labels: size/XS, verified, branch-main

#145 Add readme
  README.md
Labels: Approved-by-myakove, size/S, branch-main

#146 Dockerhub rate limit
  README.md
  webhook_server_container/dockerhub_rate_limit.py
  webhook_server_container/github_api.py
Labels: size/M, verified, branch-main

#148 test
  README.md
  example.config.yaml
  webhook_server_container/app.py
  webhook_server_container/constants.py
  webhook_server_container/github_api.py
  webhook_server_container/github_repository_settings.py
  webhook_server_container/utils.py
  webhook_server_container/webhook.py
Labels: verified, size/L, branch-main

#150 Use @ignore_exceptions()
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  webhook_server_container/github_api.py
Labels: size/M, verified, branch-main

#152 use /retest to run tests by user
  README.md
  webhook_server_container/github_api.py
Labels: verified, size/L, branch-main

#154 Update dependency poetry-dynamic-versioning to ^0.23.0
  poetry.lock
  pyproject.toml
Labels: size/XS, branch-main

#165 Refactor cherry-pick code
  README.md
  webhook_server_container/constants.py
  webhook_server_container/github_api.py
  webhook_server_container/utils.py
Labels: verified, size/L, branch-main
