Repository myk-org/github-webhook-server, pull requests merged in 2023-01, with the labels that each got.

#41 gitlab - not not add/remove undefined labels
  webhook-server-container/github_api.py
  webhook-server-container/gitlab_api.py
Labels: Approved-by-myakove, verified, size/S, branch-main

#43 github / gitlab - add / remove labels - use lowercase for comparison, support user labels
  webhook-server-container/constants.py
  webhook-server-container/github_api.py
  webhook-server-container/gitlab_api.py
Labels: Approved-by-myakove, verified, size/S, branch-main

#49 Lgtm fix
  webhook-server-container/app.py
  webhook-server-container/github_api.py
Labels: size/XS, Approved-by-myakove, branch-main

#51 Pass user to manage_reviewed_by_label
  a
  webhook-server-container/github_api.py
  webhook-server-container/gitlab_api.py
Labels: verified, size/S, branch-main

#53 Fix welcome message indentation
  webhook-server-container/github_api.py
Labels: size/XS, branch-main

#55 Support run tox
  example.config.yaml
  webhook-server-container/github_api.py
  webhook-server-container/requirements.txt
Labels: verified, size/L, branch-main

#59 test pr
  a
Labels: size/XS, branch-main

#63 Revert "test pr"
  a
Labels: size/XS, branch-main, target-version-dev1

#65 Revert "Revert "test pr""
  a
Labels: size/XS, branch-main, target-version-dev1

#67 Revert "Revert "Revert "test pr"""
  a
Labels: size/XS, branch-main, target-version-dev1

#69 Revert "Revert "Revert "Revert "test pr""""
  a
Labels: size/XS, branch-main, target-version-dev1

#71 Revert "Revert "Revert "Revert "Revert "test pr"""""
  a
Labels: size/XS, branch-main

#73 Nice log
  webhook-server-container/app.py
Labels: size/XS, branch-main, target-version-dev1

#75 auto-cherry-pick: [dev1] Nice log
  webhook-server-container/app.py
Labels: size/XS, auto-cherry-pick, branch-dev1

#77 Revert "Nice log"
  webhook-server-container/app.py
Labels: size/XS, branch-main, target-version-dev1, target-version-dev2

#79 auto-cherry-pick: [dev1] Revert "Nice log"
  webhook-server-container/app.py
Labels: size/XS, auto-cherry-pick, branch-dev1

#57 Support cherry-pick by labels
  webhook-server-container/app.py
  webhook-server-container/constants.py
  webhook-server-container/github_api.py
Labels: verified, size/L, branch-main
