Repository myk-org/github-webhook-server, pull requests merged in 2024-06, with the labels that each got.

#462 build container: checkout the right branch if PR is merged
  webhook_server_container/libs/github_api.py
Labels: size/XS, verified, branch-main

#464 Use uwsgi to run the app
  Dockerfile
  docker-compose-example.yaml
  entrypoint.sh
  poetry.lock
  pyproject.toml
  webhook_server_container/app.py
  webhook_server_container/libs/github_api.py
  webhook_server_container/utils/github_repository_settings.py
  webhook_server_container/utils/webhook.py
Labels: size/XL, verified, branch-main

#474 log success when test run success
  webhook_server_container/libs/github_api.py
Labels: size/XS, verified, branch-main

#478 delete pr tag on merge/close of a pr
  webhook_server_container/libs/github_api.py
  webhook_server_container/utils/helpers.py
Labels: size/S, branch-main

#480 Move to using FastAPI
  README.md
  docker-compose-example.yaml
  entrypoint.sh
  poetry.lock
  pyproject.toml
  renovate.json
  webhook_server_container/app.py
  webhook_server_container/libs/github_api.py
  webhook_server_container/libs/jira_api.py
  webhook_server_container/utils/constants.py
  webhook_server_container/utils/github_repository_settings.py
  webhook_server_container/utils/helpers.py
  webhook_server_container/utils/webhook.py
Labels: size/XXL, verified, branch-main, can-be-merged, approved-rnetser
