Repository myk-org/github-webhook-server, pull requests merged in 2024-11, with the labels that each got.

#623 use subprocess.PIPE for podman build commands
  webhook_server_container/libs/github_api.py
  webhook_server_container/utils/helpers.py
Labels: verified, size/S, branch-main, can-be-merged, approved-myakove, commented-coderabbitai[bot]

#624 flat `Owners` file, support owners per folder
  Dockerfile
  README.md
  pyproject.toml
  pytest.ini
  tox.ini
  tox.toml
  uv.lock
  webhook_server_container/OWNERS
  webhook_server_container/app.py
  webhook_server_container/libs/github_api.py
  webhook_server_container/tests/test_github_api.py
Labels: size/XXL, verified, branch-main, can-be-merged, approved-rnetser

#628 run_command, do not decode out and err
  webhook_server_container/libs/github_api.py
  webhook_server_container/utils/helpers.py
Labels: size/XS, branch-main, lgtm-dbasunag

#631 check only parent path for owners file, make sure root owners are alw…
  webhook_server_container/libs/github_api.py
  webhook_server_container/tests/test_github_api.py
Labels: size/XXL, verified, branch-main, commented-coderabbitai[bot], lgtm-dbasunag
