Repository myk-org/github-webhook-server, pull requests merged in 2024-07, with the labels that each got.

#484 Add future in branch protection
  webhook_server_container/libs/github_api.py
  webhook_server_container/utils/github_repository_settings.py
  webhook_server_container/utils/webhook.py
Labels: verified, size/L, branch-main, can-be-merged, approved-myakove

#486 Add Typing
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  webhook_server_container/app.py
  webhook_server_container/libs/config.py
  webhook_server_container/libs/github_api.py
  webhook_server_container/libs/jira_api.py
  webhook_server_container/utils/constants.py
  webhook_server_container/utils/dockerhub_rate_limit.py
  webhook_server_container/utils/github_repository_settings.py
  webhook_server_container/utils/helpers.py
  webhook_server_container/utils/webhook.py
Labels: size/XXL, verified, branch-main, can-be-merged, approved-myakove

#490 move process to function
  webhook_server_container/app.py
  webhook_server_container/libs/github_api.py
Labels: verified, size/S, branch-main, can-be-merged, approved-rnetser

#493 Add comment when reviewer failed to be added
  webhook_server_container/libs/github_api.py
Labels: size/XS, verified, branch-main

#495 Add command arguments to the build-and-push-container
  README.md
  example.config.yaml
  webhook_server_container/libs/github_api.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove

#497 Set approve label only if reviewer is part of approvers
  README.md
  webhook_server_container/app.py
  webhook_server_container/libs/github_api.py
  webhook_server_container/utils/constants.py
Labels: size/L, branch-main

#501 Fix where is no last commiter in commit
  Dockerfile
  webhook_server_container/libs/github_api.py
Labels: size/S, branch-main

#503 ProcessGithubWehook: do not use @ignore_exceptions
  webhook_server_container/app.py
  webhook_server_container/libs/github_api.py
  webhook_server_container/libs/jira_api.py
  webhook_server_container/utils/github_repository_settings.py
  webhook_server_container/utils/helpers.py
  webhook_server_container/utils/webhook.py
Labels: size/L, branch-main

#507 Improve logging
  README.md
  docker-compose-example.yaml
  example.config.yaml
  poetry.lock
  pyproject.toml
  webhook_server_container/app.py
  webhook_server_container/libs/config.py
  webhook_server_container/libs/github_api.py
  webhook_server_container/libs/jira_api.py
  webhook_server_container/utils/constants.py
  webhook_server_container/utils/github_repository_settings.py
  webhook_server_container/utils/helpers.py
  webhook_server_container/utils/webhook.py
Labels: size/XXL, branch-main

#511 wip label - add missing f-string
  webhook_server_container/libs/github_api.py
Labels: size/XS, branch-main

#518 Extract some code to function
  webhook_server_container/libs/github_api.py
  webhook_server_container/utils/constants.py
  webhook_server_container/utils/helpers.py
  webhook_server_container/utils/webhook.py
Labels: size/XL, verified, branch-main
