Repository myk-org/github-webhook-server, pull requests merged in 2025-05, with the labels that each got.

#741 Always return error/ok
  docker-compose-example.yaml
  pyproject.toml
  uv.lock
  webhook_server/app.py
  webhook_server/libs/exceptions.py
  webhook_server/libs/github_api.py
  webhook_server/utils/github_repository_and_webhook_settings.py
  webhook_server/utils/webhook.py
Labels: size/XXL, verified, branch-main

#744 Call get allow ips only of program started
  webhook_server/app.py
Labels: size/M, verified, branch-main

#750 Make process def async
  webhook_server/app.py
  webhook_server/libs/github_api.py
Labels: size/XS, branch-main

#752 `process_pull_request_webhook_data` - Keep username capitalization
  19
  webhook_server/libs/github_api.py
Labels: size/XS, branch-main, approved-myakove, lgtm-myakove

#756 Return response to Github in time, run our process as BackgroundTasks
  webhook_server/app.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove, lgtm-rnetser

#758 Do not log exception when it is NoPullRequestError
  webhook_server/app.py
Labels: size/XS, verified, branch-main, approved-myakove

#760 Check `is_check_run_in_progress` only if `last_commit` exists
  webhook_server/libs/github_api.py
Labels: size/XS, verified, branch-main, approved-myakove

#762 Add approve from user commnet in gh `pull_request_review`
  webhook_server/libs/github_api.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove, lgtm-myakove

#764 add/remove label: add log if user not in approvers
  webhook_server/libs/github_api.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove, lgtm-myakove

#769 Do not allow new users to run /retest or /build-and-push-container
  pyproject.toml
  uv.lock
  webhook_server/libs/config.py
  webhook_server/libs/github_api.py
  webhook_server/tests/test_pull_request_owners.py
Labels: size/XXL, branch-main

#771 Set log file path to data-dir/logs if not full path
  webhook_server/utils/helpers.py
Labels: size/XS, branch-main

#773 Split the code to classes
  webhook_server/app.py
  webhook_server/libs/check_run_handler.py
  webhook_server/libs/config.py
  webhook_server/libs/github_api.py
  webhook_server/libs/issue_comment_handler.py
  webhook_server/libs/labels_handler.py
  webhook_server/libs/pull_request_handler.py
  webhook_server/libs/pull_request_review_handler.py
  webhook_server/libs/push_handler.py
  webhook_server/libs/runner_handler.py
  webhook_server/tests/conftest.py
  webhook_server/tests/test_add_reviewer_action.py
  webhook_server/tests/test_prepare_retest_wellcome_comment.py
  webhook_server/tests/test_pull_request_owners.py
  webhook_server/tests/test_pull_request_size.py
Labels: size/XXL, verified, branch-main, commented-coderabbitai[bot]

#776 revert back to uvicorn
  Dockerfile
  entrypoint.py
  entrypoint.sh
  gunicorn.conf.py
  pyproject.toml
  uv.lock
  webhook_server/app.py
  webhook_server/utils/github_repository_and_webhook_settings.py
  webhook_server/utils/github_repository_settings.py
  webhook_server/utils/helpers.py
Labels: verified, size/L, branch-main, approved-myakove

#778 Use more async code
  .gitignore
  Dockerfile
  entrypoint.py
  entrypoint.sh
  pyproject.toml
  tox.toml
  uv.lock
  webhook_server/app.py
  webhook_server/libs/check_run_handler.py
  webhook_server/libs/config.py
  webhook_server/libs/exceptions.py
  webhook_server/libs/github_api.py
  webhook_server/libs/issue_comment_handler.py
  webhook_server/libs/labels_handler.py
  webhook_server/libs/owners_files_handler.py
  webhook_server/libs/pull_request_handler.py
  webhook_server/libs/pull_request_review_handler.py
  webhook_server/libs/push_handler.py
  webhook_server/libs/runner_handler.py
  webhook_server/tests/conftest.py
  webhook_server/tests/test_add_reviewer_action.py
  webhook_server/tests/test_prepare_retest_wellcome_comment.py
  webhook_server/tests/test_pull_request_owners.py
  webhook_server/tests/test_pull_request_size.py
  webhook_server/utils/github_repository_and_webhook_settings.py
  webhook_server/utils/github_repository_settings.py
  webhook_server/utils/helpers.py
  webhook_server/utils/webhook.py
Labels: size/XXL, verified, branch-main, approved-myakove

#785 Start process PR once it is ready_for_review
  webhook_server/libs/pull_request_handler.py
Labels: size/XS, verified, branch-main, lgtm-rnetser
