Repository myk-org/github-webhook-server, pull requests merged in 2025-03, with the labels that each got.

#674 feat: rebase pull request branch on checkout PR
  webhook_server_container/libs/github_api.py
Labels: size/XS, branch-main

#676 Add log when pull request found for check run
  webhook_server_container/libs/github_api.py
Labels: size/XS, verified, branch-main

#678 Add info to failed check runs if clone the repository failed.
  webhook_server_container/libs/github_api.py
Labels: verified, size/L, branch-main

#670 read branch protection rules from config files
  example.config.yaml
  webhook_server_container/config/schema.yaml
  webhook_server_container/tests/test_branch_protection.py
  webhook_server_container/utils/github_repository_settings.py
Labels: size/L, branch-main, approved-myakove

#680 Use merge, not rebase when running check runs
  webhook_server_container/libs/github_api.py
Labels: size/XS, branch-main

#682 Use merge origin/<branch> for check run
  webhook_server_container/libs/github_api.py
Labels: size/XS, branch-main

#684 Set repositories use repo api
  webhook_server_container/tests/test_pull_request_owners.py
  webhook_server_container/utils/github_repository_settings.py
  webhook_server_container/utils/webhook.py
Labels: verified, size/S, branch-main

#686 Use repo api token for webhooks and set repositories when available
  webhook_server_container/libs/github_api.py
  webhook_server_container/tests/conftest.py
  webhook_server_container/utils/github_repository_settings.py
  webhook_server_container/utils/helpers.py
  webhook_server_container/utils/webhook.py
Labels: verified, size/L, branch-main

#688 Refactor Config()
  webhook_server_container/app.py
  webhook_server_container/libs/config.py
  webhook_server_container/libs/github_api.py
  webhook_server_container/libs/jira_api.py
  webhook_server_container/tests/conftest.py
  webhook_server_container/tests/manifests/config.yaml
  webhook_server_container/tests/test_branch_protection.py
  webhook_server_container/tests/test_repo_data_from_config.py
  webhook_server_container/utils/constants.py
  webhook_server_container/utils/github_repository_settings.py
  webhook_server_container/utils/helpers.py
  webhook_server_container/utils/webhook.py
Labels: size/XL, verified, branch-main, commented-myakove, commented-coderabbitai[bot]
